"""Add calculation model

Revision ID: 1d409c9c6c98
Revises: 4ef1356ae538
Create Date: 2025-10-04 23:06:39.414682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d409c9c6c98'
down_revision: Union[str, Sequence[str], None] = '4ef1356ae538'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calculations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('calculation_timestamp', sa.String(), nullable=False),
    sa.Column('expected_pension', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('sex', sa.String(), nullable=False),
    sa.Column('salary', sa.String(), nullable=False),
    sa.Column('is_sick_leave_included', sa.Boolean(), nullable=False),
    sa.Column('total_accumulated_funds', sa.String(), nullable=False),
    sa.Column('year_work_start', sa.Integer(), nullable=False),
    sa.Column('year_desired_retirement', sa.Integer(), nullable=False),
    sa.Column('postal_code', sa.String(), nullable=True),
    sa.Column('jobs', sa.JSON(), nullable=False),
    sa.Column('leaves', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calculations')
    # ### end Alembic commands ###
