"""Add calculation model

Revision ID: 3c7735fad074
Revises: 1d409c9c6c98
Create Date: 2025-10-04 23:10:53.002965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '3c7735fad074'
down_revision: Union[str, Sequence[str], None] = '1d409c9c6c98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calculation_id', sa.String(), nullable=False),
    sa.Column('start_date', sa.String(), nullable=False),
    sa.Column('end_date', sa.String(), nullable=True),
    sa.Column('base_salary', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['calculation_id'], ['calculations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leaves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calculation_id', sa.String(), nullable=False),
    sa.Column('start_date', sa.String(), nullable=False),
    sa.Column('end_date', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['calculation_id'], ['calculations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('calculations', 'leaves')
    op.drop_column('calculations', 'jobs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calculations', sa.Column('jobs', sqlite.JSON(), nullable=False))
    op.add_column('calculations', sa.Column('leaves', sqlite.JSON(), nullable=False))
    op.drop_table('leaves')
    op.drop_table('jobs')
    # ### end Alembic commands ###
