"""Initial schema with DbCalculation

Revision ID: f093b4da986c
Revises: 
Create Date: 2025-10-05 06:44:30.386930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f093b4da986c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calculations',
    sa.Column('calculation_id', sa.String(length=36), nullable=False),
    sa.Column('calculation_datetime', sa.DateTime(), nullable=False),
    sa.Column('expected_pension', sa.Float(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('sex', sa.Enum('M', 'F', name='sex_enum'), nullable=False),
    sa.Column('total_accumulated_funds', sa.Float(), nullable=True),
    sa.Column('year_work_start', sa.Integer(), nullable=False),
    sa.Column('year_desired_retirement', sa.Integer(), nullable=False),
    sa.Column('postal_code', sa.String(length=16), nullable=True),
    sa.Column('jobs', sa.JSON(), nullable=False),
    sa.Column('leaves', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('calculation_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calculations')
    # ### end Alembic commands ###
